# Generated by Django 4.1.7 on 2023-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoltinToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=200)),
                ('token_creation_time', models.DateTimeField()),
                ('token_end_time', models.DateTimeField()),
            ],
        ),
    ]
