# Generated by Django 4.1.7 on 2023-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_moltintoken_token_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moltintoken',
            name='access_token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='moltintoken',
            name='token_creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moltintoken',
            name='token_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
