# Generated by Django 4.1.7 on 2023-03-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='address_pizzeria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
