# Generated by Django 4.1.7 on 2023-03-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_telegramuser_address_pizzeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='moltintoken',
            name='active_token',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
